# Common params

serving port:                 :1234
mysql connection string:      root:root@tcp(127.0.0.1:3305)/works
postgres connection string:   user=root password=root dbname=onlinebc sslmode=disable
redis connection string:      127.0.0.1:6389
redis TTL:                    60    

#postgres connection string: postgres://root:root@localhost/onlinebc?sslmode=disable